exam/urls.py
from django.urls import path, include
from . import views

app_name = 'exam'

urlpatterns = [
    path('', views.index, name='index'),
    path('multiple_choice/<int:exam_id>/', views.multiple_choice, name='multiple_choice'),
    path('structured/<int:exam_id>/', views.structured, name='structured'),
    path('proctor/', views.proctor, name='proctor'),
    path('alert/', views.alert, name='alert'),

]

proctor/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from exam.views import disqualified

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('exam.urls')),
    path('disqualified/', disqualified, name='disqualified'),

]

exam/models.py
from django.db import models
from django.conf import settings

EXAM_TYPES = (
    ("Multiple Choice", "Multiple Choice"),
    # ("Structured", "Structured")
)


class Exam(models.Model):
    name = models.CharField(max_length=100)
    exam_type = models.CharField(max_length=100, choices=EXAM_TYPES)
    start_time = models.CharField(max_length=100)
    endtime = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class ExamQuestion(models.Model):
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
    question = models.TextField()
    answer1 = models.TextField()
    answer2 = models.TextField()
    answer3 = models.TextField()
    answer4 = models.TextField()

    def __str__(self):
        return self.question

    class Meta:
        verbose_name_plural = "Multiple Choice Exam Questions"


class StructuredQuestion(models.Model):
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
    question = models.TextField()

    def __str__(self):
        return self.question

    class Meta:
        verbose_name_plural = "Structured Exam Questions"

class Alert(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username + " - " + str(self.date)


# class UserAnswer(models.Model):
#     exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
#     user = models.ForeignKey(settings.AUTH_USER_MODEL,
#                              on_delete=models.CASCADE)
#     answers = models.CharField()
#
#
class Answer(models.Model):
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
    question = models.ForeignKey(ExamQuestion, on_delete=models.CASCADE)
    answer = models.TextField()

    def __str__(self):
        return f"{self.exam} - {self.question} - {self.answer}"

    class Meta:
        verbose_name_plural = "Multiple Choice Answers"


class ExamDuration(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    time_started = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.time_started)


class Disqualified(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Disqualified'

    def __str__(self):
        return self.user.username

exam/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
import threading
import winsound
from datetime import datetime
from datetime import date
import cv2
import imutils
from .models import Alert, Exam, ExamQuestion, Answer, StructuredQuestion, ExamDuration, Disqualified
from django.http import HttpResponse


def index(request):
    mutiple_choice_exam = Exam.objects.filter(exam_type="Multiple Choice")
    structured_exam = Exam.objects.filter(exam_type="Structured")
    context = {'multiple_choice_exam': mutiple_choice_exam, 'structured_exam': structured_exam}
    return render(request, 'exam/index.html', context)


@login_required()
def multiple_choice(request, exam_id):
    exam = Exam.objects.get(id=exam_id)
    exam_questions = ExamQuestion.objects.filter(exam=exam)
    answers = Answer.objects.filter(exam=exam)
    endtime = exam.endtime
    start_time = exam.endtime
    context = {'exam': exam, 'exam_questions': exam_questions, 'answers': answers, 'endtime': endtime, 'start_time': start_time}
    return render(request, 'exam/multiple_choice.html', context)


@login_required()
def structured(request, exam_id):
    exam = Exam.objects.get(id=exam_id)
    exam_questions = StructuredQuestion.objects.filter(exam=exam)
    context = {'exam': exam, 'exam_questions': exam_questions}
    return render(request, 'exam/structured.html', context)


@login_required()
def proctor(request):
    user = request.user
    ExamDuration.objects.create(user=user)
    cap = cv2.VideoCapture(0, cv2.CAP_DSHOW)
    cap.set(cv2.CAP_PROP_FRAME_WIDTH, 640)
    cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 480)

    _, start_frame = cap.read()
    start_frame = imutils.resize(start_frame, width=500)
    # Removing any colours
    start_frame = cv2.cvtColor(start_frame, cv2.COLOR_BGR2GRAY)

    # Smoothening the video
    start_frame = cv2.GaussianBlur(start_frame, (21, 21), 0)

    alarm = False
    # Press t to toggle alarm
    alarm_mode = True
    # Amount of movement to turn on alarm
    alarm_counter = 0

    def beep_alarm():
        global alarm
        for _ in range(5):
            if not alarm_mode:
                break
            print("alarm")
            winsound.Beep(2500, 1000)
        alarm = False

    while True:
        _, frame = cap.read()
        frame = imutils.resize(frame, width=500)

        if alarm_mode:
            frame_bw = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
            frame_bw = cv2.GaussianBlur(frame_bw, (5, 5), 0)
            difference = cv2.absdiff(frame_bw, start_frame)
            threshold = cv2.threshold(difference, 25, 255, cv2.THRESH_BINARY)[1]
            start_frame = frame_bw

            if threshold.sum() > 300:
                alarm_counter += 1
            else:
                if alarm_counter > 0:
                    alarm_counter -= 1

            cv2.imshow("Cam", threshold)
        else:
            cv2.imshow("Cam", frame)

        if alarm_counter > 50:
            if not alarm:
                alarm = True
                threading.Thread(target=beep_alarm).start()
                Alert.objects.create(user=user)



        key_pressed = cv2.waitKey(30)
        if key_pressed == ord("t"):
            alarm_mode = not alarm_mode
            alarm_counter = 0
        if key_pressed == ord("q"):
            alarm_mode = False
            break

    cap.release()
    cv2.destroyAllWindows()
    return render(request, 'exam/proctor.html')


def alert(request):
    alerts = Alert.objects.all()
    context = {'alerts': alerts}
    return render(request, 'exam/alert.html', context)


def disqualified(request):
    user = request.user
    Disqualified.objects.create(user=user)
    success = user, ", you have been disqualified!"
    return HttpResponse(success)

exam/templates/exam/alert.html
{% extends 'base.html' %}
{% block title %}Alert{% endblock title %}
{% block content %}
{#    <h1>These are the alerts</h1>#}
{#    {% for alert in alerts %}#}
{#        {{ alert.user.username }} | {{ alert.date }}#}
{#    {% empty %}#}
{#        <li>No funny movements recorded in the exam</li>#}
{#    {% endfor %}#}
     <div>
        <section class="py-4 py-xl-5">
            <div class="container">
                <div class="row mb-5">
                    <div class="col-md-8 col-xl-6 text-center mx-auto">
                        <h2>Alerts</h2>
                        <p>Alerts are when a student suspiciously moves in the exam.  The time of the movement is recorded down below.</p>
                    </div>
                </div>
            </div>
            <section class="mt-4">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col">
                            <div class="card shadow">
                                <div class="card-header py-2">
                                    <p class="lead text-info m-0"><strong>Our proctor software deemed the following students as having malicious activity in the exam room.</strong></p>
                                </div>
                                <div class="card-body">
                                    <div class="table-responsive table mb-0 pt-3 pe-2">
                                        <table class="table table-striped table-sm my-0 mydatatable">
                                            <thead>
                                                <tr>
                                                    <th>Reg Number</th>
                                                    <th>ID(in database)</th>
                                                    <th>Date</th>
                                                </tr>
                                            </thead>
                                            {% for alert in alerts %}
                                            <tbody>
                                                <tr>
                                                    <td>{{ alert.user.username }}</td>
                                                    <td>{{ alert.user.id }}</td>
                                                    <td>{{ alert.date }}</td>
                                                </tr>
                                            {% empty %}
                                                 <tr>
                                                    <td>None</td>
                                                    <td>0</td>
                                                    <td>0</td>
                                                </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </section>
{#     <section class="py-4 py-xl-5">#}
{#            <div class="container">#}
{#                <div class="text-center p-4 p-lg-5">#}
{#                    <p class="fw-bold text-primary mb-2">Proud to introduce</p>#}
{#                    <h1 class="fw-bold mb-4">Online Proctor system, we are with you everywhere!</h1><button class="btn btn-primary fs-5 me-2 py-2 px-4" type="button">Learn more.</button><button class="btn btn-light fs-5 py-2 px-4" type="button">Discover</button>#}
{#                </div>#}
{#            </div>#}
{#     </section>#}
    </div>
{% endblock content %}

exam/templates/exam/index.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}Home{% endblock title %}
</head>
<body>
    {% block content %}

         <div>
        <section class="py-4 py-xl-5">
            <div class="container">
                <div class="row mb-5">
                    <div class="col-md-8 col-xl-6 text-center mx-auto">
                        <h2>Available Examinations</h2>
                        <p>The following are the available examinations as from the current date.</p>
                    </div>
                </div>
            </div>
            <section class="mt-4">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col">
                            <div class="card shadow">
                                <div class="card-header py-2">
                                    <p class="lead text-info m-0"><strong>No cheating should be allowed when writing these exams.</strong></p>
                                </div>
                                <div class="card-body">
                                    <div class="table-responsive table mb-0 pt-3 pe-2">
                                        <table class="table table-striped table-sm my-0 mydatatable">
                                            <thead>
                                                <tr>
                                                    <th>Module</th>
                                                    <th>Exam Type</th>
                                                    <th>Date</th>
                                                </tr>
                                            </thead>
                                            {% for exam in multiple_choice_exam %}
                                            <tbody>
                                                <tr>

                                                    <td><a href="{% url 'exam:multiple_choice' exam.id %}">{{ exam.name }}</a></td>
                                                    <td>{{ exam.exam_type }}</td>
                                                    <td>{{ exam.start_time }}</td>
                                                </tr>
{#                                            {% empty %}#}
{#                                                 <tr>#}
{#                                                    <td>None</td>#}
{#                                                    <td>0</td>#}
{#                                                    <td>0</td>#}
{#                                                </tr>#}

                                            </tbody>
                                            {% endfor %}
{#                                         {% for exam in structured_exam %}#}
{#                                            <tbody>#}
{#                                                <tr>#}
{##}
{#                                                    <td><a href="{% url 'exam:structured' exam.id %}">{{ exam.name }}</a></td>#}
{#                                                    <td>{{ exam.exam_type }}</td>#}
{#                                                    <td>{{ exam.start_time }}</td>#}
{#                                                </tr>#}
{#                                            {% empty %}#}
{#                                                 <tr>#}
{#                                                    <td>None</td>#}
{#                                                    <td>0</td>#}
{#                                                    <td>0</td>#}
{#                                                </tr>#}
{##}
{#                                            </tbody>#}
{#                                            {% endfor %}#}
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </section>


{#         <section class="py-4 py-xl-5">#}
{#            <div class="container">#}
{#                <div class="text-center p-4 p-lg-5">#}
{#                    <p class="fw-bold text-primary mb-2">Proud to introduce</p>#}
{#                    <h1 class="fw-bold mb-4">Online Proctor system, we are with you everywhere!</h1><button class="btn btn-primary fs-5 me-2 py-2 px-4" type="button">Learn more.</button><button class="btn btn-light fs-5 py-2 px-4" type="button">Discover</button>#}
{#                </div>#}
{#            </div>#}
{#        </section>#}
    </div>
    {% endblock content %}
</body>
</html>

exam/templates/exam/multiple_choice.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}Multiple Choice Questions{% endblock title %}

</head>
<body>
    {% block content %}
{#        <a href="{% url 'exam:proctor' %}" target="_blank" rel="noopener noreferrer">Start</a>#}
{#        <H1>{{ exam.name }}</H1>#}

        <!-- Top Section -->
{#            <div class="intro py-3 bg-white text-center">#}
{#                <div class="container">#}
{##}
{#                    <h2><a href="{% url 'exam:proctor' %}" target="_blank" rel="noopener noreferrer" class="text-primary display-3 my-4">Start</a></h2>#}
{#                </div>#}
{#            </div>#}
        <section class="py-4 py-xl-5">
                    <div class="container">
                        <div class="row mb-5">
                            <div class="col-md-8 col-xl-6 text-center mx-auto">
                                <h2>{{ exam.name }}</h2>
                                <a class="invigilate d-none" href="{% url 'exam:proctor' %}" target="_blank" rel="noopener noreferrer">Click here to start being invigilated</a>
                                <p id="demo"></p>
                            </div>
                        </div>
                    </div>
        </section>

            <!-- Result Section -->
            <div class="result py-4 d-none bg-light text-center">
                <div class="container lead">
                    <p>Your score is: <span class="text-primary display-4 p-3">0%</span></p>


                </div>
            </div>
            {% for answer in answers %}
                <p class="answers d-none">{{ answer.answer }}</p>

            {% endfor %}

            <!-- Quiz Section -->
        <div class="bg-light border rounded border-light jumbotron py-5 px-4">

            <div class="quiz py-4 bg-light">
{#            <div class="quiz py-4 bg-primary">#}
                <div class="container">
                    <h2 class="my-5 text-dark">
                        On with the questions...
                    </h2>

                    <form class="quiz-form d-none text-dark structured-form">
                        {% for exam_question in exam_questions %}
                            <div class="my-5">
                                <p class="lead font-wight-normal">{{ exam_question.question }}</p>
                                <div class="form-check my-2 text-dark-50">
                                    <input type="radio" name="q{{ exam_question.id }}" value="A" checked>
                                    <label class="form-check-label">{{ exam_question.answer1 }}</label>
                                </div>
                                <div class="form-check my-2 text-dark-50">
                                    <input type="radio" name="q{{ exam_question.id }}" value="B">
                                    <label class="form-check-label">{{ exam_question.answer2 }}</label>
                                </div>
                                <div class="form-check my-2 text-dark-50">
                                    <input type="radio" name="q{{ exam_question.id }}" value="C">
                                    <label class="form-check-label">{{ exam_question.answer3 }}</label>
                                </div>
                                <div class="form-check my-2 text-dark-50">
                                    <input type="radio" name="q{{ exam_question.id }}" value="D">
                                    <label class="form-check-label">{{ exam_question.answer4 }}</label>
                                </div>
                            </div>


                        {% endfor %}
                            <div class="text-center">
                                <input class="score" type="submit" class="btn btn-light">
                            </div>


                    </form>

                </div>

            </div>
            </div>

        <p class="examDate d-none">{{ exam.endtime }}</p>
        <p class="examDateStart d-none">{{ exam.start_time }}</p>
{#        <section class="py-4 py-xl-5">#}
{#            <div class="container">#}
{#                <div class="text-center p-4 p-lg-5">#}
{#                    <p class="fw-bold text-primary mb-2">Proud to introduce</p>#}
{#                    <h1 class="fw-bold mb-4">Online Proctor system, we are with you everywhere!</h1><button class="btn btn-primary fs-5 me-2 py-2 px-4" type="button">Learn more.</button><button class="btn btn-light fs-5 py-2 px-4" type="button">Discover</button>#}
{#                </div>#}
{#            </div>#}
{#        </section>#}

{#       <div class="carousel slide" data-bs-ride="false" id="carousel-1">#}
{#            <div class="carousel-inner">#}
{#                <div class="carousel-item active"><img class="w-100 d-block" src="{% static '/assets/img/quiz-examples-768x388.png' %}" alt="Slide Image" height="500" width="100"></div>#}
{#                <div class="carousel-item"><img class="w-100 d-block" src="{% static '/assets/img/linear-regression-in-machine-learning.png' %}" alt="Slide Image" height="500" width="100"></div>#}
{#            </div>#}
{#            <div><a class="carousel-control-prev" href="#carousel-1" role="button" data-bs-slide="prev"><span class="carousel-control-prev-icon"></span><span class="visually-hidden">Previous</span></a><a class="carousel-control-next" href="#carousel-1" role="button" data-bs-slide="next"><span class="carousel-control-next-icon"></span><span class="visually-hidden">Next</span></a></div>#}
{#            <ol class="carousel-indicators">#}
{#                <li data-bs-target="#carousel-1" data-bs-slide-to="0" class="active"></li>#}
{#                <li data-bs-target="#carousel-1" data-bs-slide-to="1"></li>#}
{#            </ol>#}
{#        </div>#}



    {% endblock content %}
</body>
</html>

exam/templates/exam/proctor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Exam end</title>
</head>
<body>
<p class="clock">Exam ended on..</p>
</body>
</html>

exam/templates/exam/structured.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}Structured Questions{% endblock title %}

</head>
<body>
    {% block content %}
{#        <a href="{% url 'exam:proctor' %}" target="_blank" rel="noopener noreferrer">Start</a>#}
{#        <H1>{{ exam.name }}</H1>#}

        <!-- Top Section -->
{#            <div class="intro py-3 bg-white text-center">#}
{#                <div class="container">#}
{##}
{#                    <h2><a href="{% url 'exam:proctor' %}" target="_blank" rel="noopener noreferrer" class="text-primary display-3 my-4">Start</a></h2>#}
{#                </div>#}
{#            </div>#}

            <!-- Result Section -->
{#            <div class="result py-4 d-none bg-light text-center">#}
{#                <div class="container lead">#}
{#                    <p>You are <span class="text-primary display-4 p-3">0%</span> ninja</p>#}
{#                </div>#}
{#            </div>#}


            <!-- Quiz Section -->
            <div class="structured">
                <section class="py-4 py-xl-5">
                    <div class="container">
                        <div class="row mb-5">
                            <div class="col-md-8 col-xl-6 text-center mx-auto">
                                <h2>{{ exam.name }}</h2>
                                <a class="invigilate d-none" href="{% url 'exam:proctor' %}" target="_blank" rel="noopener noreferrer">Click here to start being invigilated</a>
                                <p id="demo"></p>
                            </div>
                        </div>
                    </div>
                </section>
                <div class="result py-4 d-none bg-light text-center">
                <div class="container lead">
                    <p>Your mark is: <span class="text-primary structured-primary display-4 p-3">0%</span></p>


                </div>
            </div>
                <div class="bg-light border rounded border-light jumbotron py-5 px-4">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">Exam Questions</h4>
                            <h6 class="text-muted card-subtitle mb-2">Pease note marks will be given for long answers.</h6>
                            <form class="structured-form d-none long-answer-form">
                                {% for question in exam_questions %}
                                <p>{{ question.question }}</p><textarea name="q{{ question.id }}" class="form-control long-answer-textarea"></textarea>
{#                                {% empty %}#}
{#                                <li>Exam not yet set.</li>#}
                                {% endfor %}
{#                                <p>Selectionner le nom pour l'upload</p><textarea class="form-control"></textarea>#}
                                <div class="mt-4"><button class="btn btn-success btn-lg score long-answer-btn" type="submit">Submit</button></div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
{#        {% for answer in answers %}#}
{##}
{#                <p class="answers">{{ answer.answer }}</p>#}
{##}
{#        {% endfor %}#}
        <p class="examDate d-none">{{ exam.endtime }}</p>
        <p class="examDateStart d-none">{{ exam.start_time }}</p>
{#        <section class="py-4 py-xl-5">#}
{#            <div class="container">#}
{#                <div class="text-center p-4 p-lg-5">#}
{#                    <p class="fw-bold text-primary mb-2">Proud to introduce</p>#}
{#                    <h1 class="fw-bold mb-4">Online Proctor system, we are with you everywhere!</h1><button class="btn btn-primary fs-5 me-2 py-2 px-4" type="button">Learn more.</button><button class="btn btn-light fs-5 py-2 px-4" type="button">Discover</button>#}
{#                </div>#}
{#            </div>#}
{#        </section>#}



    {% endblock content %}
</body>
</html>