exam/urls.py
from django.urls import path, include
from . import views

app_name = 'exam'

urlpatterns = [
    path('', views.index, name='index'),
    path('multiple_choice/<int:exam_id>/', views.multiple_choice, name='multiple_choice'),
    path('structured/<int:exam_id>/', views.structured, name='structured'),
    path('proctor/', views.proctor, name='proctor'),
    path('alert/', views.alert, name='alert'),

]

proctor/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from exam.views import disqualified

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('exam.urls')),
    path('disqualified/', disqualified, name='disqualified'),

]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register')
]

exam/models.py
from django.db import models
from django.conf import settings

EXAM_TYPES = (
    ("Multiple Choice", "Multiple Choice"),
    # ("Structured", "Structured")
)


class Exam(models.Model):
    name = models.CharField(max_length=100)
    exam_type = models.CharField(max_length=100, choices=EXAM_TYPES)
    start_time = models.CharField(max_length=100)
    endtime = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class ExamQuestion(models.Model):
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
    question = models.TextField()
    answer1 = models.TextField()
    answer2 = models.TextField()
    answer3 = models.TextField()
    answer4 = models.TextField()

    def __str__(self):
        return self.question

    class Meta:
        verbose_name_plural = "Multiple Choice Exam Questions"


class StructuredQuestion(models.Model):
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
    question = models.TextField()

    def __str__(self):
        return self.question

    class Meta:
        verbose_name_plural = "Structured Exam Questions"

class Alert(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username + " - " + str(self.date)


# class UserAnswer(models.Model):
#     exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
#     user = models.ForeignKey(settings.AUTH_USER_MODEL,
#                              on_delete=models.CASCADE)
#     answers = models.CharField()
#
#
class Answer(models.Model):
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
    question = models.ForeignKey(ExamQuestion, on_delete=models.CASCADE)
    answer = models.TextField()

    def __str__(self):
        return f"{self.exam} - {self.question} - {self.answer}"

    class Meta:
        verbose_name_plural = "Multiple Choice Answers"


class ExamDuration(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    time_started = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.time_started)


class Disqualified(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Disqualified'

    def __str__(self):
        return self.user.username

exam/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
import threading
import winsound
from datetime import datetime
from datetime import date
import cv2
import imutils
from .models import Alert, Exam, ExamQuestion, Answer, StructuredQuestion, ExamDuration, Disqualified
from django.http import HttpResponse


def index(request):
    mutiple_choice_exam = Exam.objects.filter(exam_type="Multiple Choice")
    structured_exam = Exam.objects.filter(exam_type="Structured")
    context = {'multiple_choice_exam': mutiple_choice_exam, 'structured_exam': structured_exam}
    return render(request, 'exam/index.html', context)


@login_required()
def multiple_choice(request, exam_id):
    exam = Exam.objects.get(id=exam_id)
    exam_questions = ExamQuestion.objects.filter(exam=exam)
    answers = Answer.objects.filter(exam=exam)
    endtime = exam.endtime
    start_time = exam.endtime
    context = {'exam': exam, 'exam_questions': exam_questions, 'answers': answers, 'endtime': endtime, 'start_time': start_time}
    return render(request, 'exam/multiple_choice.html', context)


@login_required()
def structured(request, exam_id):
    exam = Exam.objects.get(id=exam_id)
    exam_questions = StructuredQuestion.objects.filter(exam=exam)
    context = {'exam': exam, 'exam_questions': exam_questions}
    return render(request, 'exam/structured.html', context)


@login_required()
def proctor(request):
    user = request.user
    ExamDuration.objects.create(user=user)
    cap = cv2.VideoCapture(0, cv2.CAP_DSHOW)
    cap.set(cv2.CAP_PROP_FRAME_WIDTH, 640)
    cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 480)

    _, start_frame = cap.read()
    start_frame = imutils.resize(start_frame, width=500)
    # Removing any colours
    start_frame = cv2.cvtColor(start_frame, cv2.COLOR_BGR2GRAY)

    # Smoothening the video
    start_frame = cv2.GaussianBlur(start_frame, (21, 21), 0)

    alarm = False
    # Press t to toggle alarm
    alarm_mode = True
    # Amount of movement to turn on alarm
    alarm_counter = 0

    def beep_alarm():
        global alarm
        for _ in range(5):
            if not alarm_mode:
                break
            print("alarm")
            winsound.Beep(2500, 1000)
        alarm = False

    while True:
        _, frame = cap.read()
        frame = imutils.resize(frame, width=500)

        if alarm_mode:
            frame_bw = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
            frame_bw = cv2.GaussianBlur(frame_bw, (5, 5), 0)
            difference = cv2.absdiff(frame_bw, start_frame)
            threshold = cv2.threshold(difference, 25, 255, cv2.THRESH_BINARY)[1]
            start_frame = frame_bw

            if threshold.sum() > 300:
                alarm_counter += 1
            else:
                if alarm_counter > 0:
                    alarm_counter -= 1

            cv2.imshow("Cam", threshold)
        else:
            cv2.imshow("Cam", frame)

        if alarm_counter > 50:
            if not alarm:
                alarm = True
                threading.Thread(target=beep_alarm).start()
                Alert.objects.create(user=user)



        key_pressed = cv2.waitKey(30)
        if key_pressed == ord("t"):
            alarm_mode = not alarm_mode
            alarm_counter = 0
        if key_pressed == ord("q"):
            alarm_mode = False
            break

    cap.release()
    cv2.destroyAllWindows()
    return render(request, 'exam/proctor.html')


def alert(request):
    alerts = Alert.objects.all()
    context = {'alerts': alerts}
    return render(request, 'exam/alert.html', context)


def disqualified(request):
    user = request.user
    Disqualified.objects.create(user=user)
    success = user, ", you have been disqualified!"
    return HttpResponse(success)

exam/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static '/assets/bootstrap/css/bootstrap.min.css' %}">
{#    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.5/css/buttons.dataTables.min.css">#}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.21/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.2/css/theme.bootstrap_4.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css">
    <link rel="stylesheet" href="{% static '/assets/css/Ludens---Dark-Mode-Admin-Dashboard.css' %}">
    <link rel="stylesheet" href="{% static '/assets/css/Navbar-Right-Links-Dark-icons.css' %}">
{#    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.5/css/buttons.dataTables.min.css">#}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.21/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.2/css/theme.bootstrap_4.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css">
    <link rel="stylesheet" href="{% static '/assets/css/Ludens---Dark-Mode-Admin-Dashboard.css' %}">
    <link rel="stylesheet" href="{% static '/assets/css/Navbar-Right-Links-Dark-icons.css' %}">
</head>
<body>
    <nav class="navbar navbar-dark navbar-expand-md bg-dark py-3">
        <div class="container"><a class="navbar-brand d-flex align-items-center" href="#"><span class="bs-icon-sm bs-icon-rounded bs-icon-primary d-flex justify-content-center align-items-center me-2 bs-icon"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-eye-fill">
                        <path fill-rule="evenodd" d="M0 10.5A1.5 1.5 0 0 1 1.5 9h1A1.5 1.5 0 0 1 4 10.5v1A1.5 1.5 0 0 1 2.5 13h-1A1.5 1.5 0 0 1 0 11.5v-1zm1.5-.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1zm10.5.5A1.5 1.5 0 0 1 13.5 9h1a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1-1.5 1.5h-1a1.5 1.5 0 0 1-1.5-1.5v-1zm1.5-.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1zM6 4.5A1.5 1.5 0 0 1 7.5 3h1A1.5 1.5 0 0 1 10 4.5v1A1.5 1.5 0 0 1 8.5 7h-1A1.5 1.5 0 0 1 6 5.5v-1zM7.5 4a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1z"></path>
                        <path d="M6 4.5H1.866a1 1 0 1 0 0 1h2.668A6.517 6.517 0 0 0 1.814 9H2.5c.123 0 .244.015.358.043a5.517 5.517 0 0 1 3.185-3.185A1.503 1.503 0 0 1 6 5.5v-1zm3.957 1.358A1.5 1.5 0 0 0 10 5.5v-1h4.134a1 1 0 1 1 0 1h-2.668a6.517 6.517 0 0 1 2.72 3.5H13.5c-.123 0-.243.015-.358.043a5.517 5.517 0 0 0-3.185-3.185z"></path>
                    </svg></span><span>APOES</span></a><button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-5"><span class="visually-hidden">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navcol-5">
                <ul class="navbar-nav ms-auto">
                    {% if request.user.is_authenticated %}
                            <li class="nav-item"><a class="nav-link active" href="{% url 'exam:index' %}">Home</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'exam:alert' %}">Alerts</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'users:logout' %}">Logout</a></li>
                        </ul><a class="btn btn-primary ms-md-2" role="button" href="#">{{ request.user.username }}</a>
                    {% else %}
                            <li class="nav-item"><a class="nav-link active" href="{% url 'exam:index' %}">Home</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'exam:alert' %}">Alerts</a></li>
{#                            <li class="nav-item"><a class="nav-link" href="#">Third Item</a></li>#}
                        </ul><a class="btn btn-primary ms-md-2" role="button" href="{% url 'users:login' %}">SignUp/Login</a>
                    {% endif %}
            </div>
        </div>
    </nav>
{#    <a href="{% url 'exam:index' %}">Home</a> |#}
{#    {% if request.user.is_authenticated %}#}
{#        <a href="{% url 'exam:alert' %}">Alert</a>#}
{#        Hello, {{ user.username }}.#}
{#        <a href="{% url 'users:logout' %}">Log out</a>#}
{#    {% else %}#}
{#        <a href="{% url 'users:register' %}">Register</a>#}
{#        <a href="{% url 'users:login' %}">Log in</a>#}
{#    {% endif %}#}
    {% block content %}
    {% endblock content %}
    <footer class="text-center bg-dark">
        <div class="container text-white py-4 py-lg-5">
            <ul class="list-inline">
                <li class="list-inline-item me-4"><a class="link-light" href="#">About Us</a></li>
                <li class="list-inline-item me-4"><a class="link-light" href="#">Contact Us</a></li>
                <li class="list-inline-item"><a class="link-light" href="#">Help</a></li>
            </ul>
            <ul class="list-inline">
                <li class="list-inline-item me-4"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-facebook text-light">
                        <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"></path>
                    </svg></li>
                <li class="list-inline-item me-4"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-twitter text-light">
                        <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"></path>
                    </svg></li>
                <li class="list-inline-item"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-instagram text-light">
                        <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"></path>
                    </svg></li>
            </ul>
            <p class="text-muted mb-0">Copyright © 2023 AI Proctoring Online Examination System.</p>
        </div>
    </footer>

    <script src="{% static '/js/sandbox.js' %}"></script>
    <script src="{% static '/js/app.js' %}"></script>
    <script src="{% static '/js/countdown.js' %}"></script>
     <script src="{% static '/js/monitor.js' %}"></script>
    <script src="{% static '/js/longAnswers.js' %}"></script>
    <script src="{% static '/assets/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.6.0/umd/popper.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.21/js/jquery.dataTables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.21/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.print.min.js"></script>
    <script src="{% static '/assets/js/DataTable---Fully-BSS-Editable-style.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.2/js/jquery.tablesorter.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.2/js/widgets/widget-filter.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.2/js/widgets/widget-storage.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="{% static '/assets/js/Ludens---Dark-Mode-Admin-Dashboard-Ludens---1-Index-Table-with-Search--Sort-Filters-v20-1.js' %}"></script>
    <script src="{% static '/assets/js/Ludens---Dark-Mode-Admin-Dashboard-Ludens---1-Index-Table-with-Search--Sort-Filters-v20.js' %}"></script>
    <script src="{% static '/assets/js/Ludens---Dark-Mode-Admin-Dashboard-Ludens---Sleek-Image-Input-with-Preview.js' %}"></script>
    <script src="{% static '/assets/js/Ludens---Dark-Mode-Admin-Dashboard-main.js' %}"></script>
    <script src="{% static '/assets/js/Ludens---Dark-Mode-Admin-Dashboard-main.js' %}"></script>
    <script src="{% static '/assets/js/Ludens---Dark-Mode-Admin-Dashboard-theme.js' %}"></script>

</body>
</html>